image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: 'echo "TODO: Replace with command to start project"'

vscode:
  extensions:
    - esbenp.prettier-vscode@5.8.0:cd2Jz796EPVnD5zeCyctPw==
    - amazonwebservices.aws-toolkit-vscode@1.18.0:wlFDViT+R10QIqDiaBNRWg==