AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: |
  lambda-container-fuse-workers
  Sample SAM Template for lambda-container-fuse-workers
Globals:
  Function:
    Timeout: 3
Resources:
  LambdaFuseFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        LambdaFuse:
          Type: Api
          Properties:
            Path: /search
            Method: ANY
      ImageUri: 020121159233.dkr.ecr.us-east-1.amazonaws.com/lambda-fuse:latest
      MemorySize: 10240
      Timeout: 30
      Policies:
        - AWSXrayWriteOnlyAccess
Outputs:
  LambdaFuseApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/search/
  LambdaFuseFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt LambdaFuseFunction.Arn
  LambdaFuseFunctionIamRole:
    Description: Implicit IAM Role created for Lambda Fuse function
    Value: !GetAtt LambdaFuseFunctionRole.Arn
