AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-container-fuse-workers

  Sample SAM Template for lambda-container-fuse-workers

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  LambdaFuseFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events:
        LambdaFuse:
          Type: Api
          Properties:
            Path: /search
            Method: ANY
    Metadata:
      DockerTag: nodejs12.x-v1
      DockerContext: ./lambda-fuse
      Dockerfile: Dockerfile

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LambdaFuseApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  LambdaFuseFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt LambdaFuseFunction.Arn
  LambdaFuseFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt LambdaFuseFunctionRole.Arn
